run_static_analysis_task:
  description: >
    Conduct an in-depth analysis to identify potential security vulnerabilities across
    the specified systems, applications, or infrastructure. Focus on emerging threats and vulnerabilities
    as of 2024.
  expected_output: >
    A list of 10 security vulnerabilities, each with a brief description, the affected systems, and the 
    potential risks associated with them.
  agent: static_analyzer

scan_dependencies_task:
  description: >
    Analyze a given security incident to identify the root cause, affected systems, and extent of impact.
    Trace the vulnerability back to its source and document the findings.
  expected_output: >
    A detailed report outlining the root cause, affected components, timeline of the incident,
    and recommendations for immediate mitigation.
  agent: dependency_scanner

remediation_task:
  description: >
    Create a plan to remediate the identified vulnerabilities or fix the root cause of a given incident.
    Develop patches or configuration changes required to secure the system.
  expected_output: >
    A step-by-step remediation guide including code snippets, system configurations,
    or process updates to resolve the identified issue.
  agent: remediation_engineer

remediation_validation_task:
  description: >
    Verify that the implemented fixes or patches have resolved the identified vulnerabilities
    without introducing new issues. Test for completeness and effectiveness.
  expected_output: >
    A validation report confirming successful remediation, including test results and 
    any additional adjustments required.
  agent: remediation_engineer

clone_repository_task:
  description: >
    Clone a specified GitHub repository to a local directory. Ensure the repository is 
    correctly cloned with all branches and commits. Clone the repo at this url {repo_url}
  expected_output: >
    The local path where the repository has been cloned, including all branches and commits.
  agent: repository_cloner

detect_secrets_task:
  description: >
    Scan the specified repository for any exposed secrets such as API keys, passwords, or other sensitive information.
    Use tools like Git Secrets or TruffleHog to perform the scan.
  expected_output: >
    A list of detected secrets, including the file paths, lines where the secrets were found, and the type of secret.
  agent: secret_detector
